build:
	./build.sh
run:
	/root/bf-sde-8.2.0/run_switchd.sh -p AHashFlow
push:
	git add -A
	git commit -m "Automatic uploading. No comments!"
	git push
pull:
	git pull
register:
	python ReadRegister.py
